---
data:
  z: 1.0
  nbar: 1.e-4
  simulation: quijote
  finder: 'FoF'
  hodmodel: zheng07
  
datacuts:
  ells: "024"
  kmax: 0.5
  kmin: 0.005
  logit: False
  standardize: True
  ampnorm: False
  offset_amp: 1.e+4
  ngals: True

analysis:
  seed: 0
  train_frac: 0.85
  fithod: True
  standardize_hod: True
  suffix: ""
  ndiagnostics: 5