---
data:
  z: 1.0
  nbar: 4.5e-4
  simulation: quijote
  finder: 'combine'
  hodmodel: zheng07_velab
  
datacuts:
  ells: "024"
  kmax: 0.5
  kmin: 0.005
  logit: False
  standardize: True
  ampnorm: False
  offset_amp: 1.e+4
  ngals: True

analysis:
  seed: 0
  train_fraction: 0.85
  validation_fraction: 0.2
  fithod: True
  standardize_hod: True
  suffix: ""
  ndiagnostics: 5