---
data:
  z: 0.5
  nbar: 4.e-4
  simulation: fastpm
  finder: 'FoF'
  hodmodel: zheng07_velab
  
datacuts:
  ells: "024"
  kmax: 0.5
  kmin: 0.005
  logit: False
  standardize: True
  ampnorm: False
  offset_amp: 1.e+4
  ngals: False

analysis:
  seed: 0
  train_fraction: 0.85
  validation_fraction: 0.06
  fithod: True
  standardize_hod: True
  suffix: "-train94"
  ndiagnostics: 5