---
data:
  z: 1.0
  nbar: 4.5e-4
  simulation: quijote
  finder: 'Rockstar'
  hodmodel: zheng07_velab
  
datacuts:
  ells: "024"
  kmax_pk: 0.5
  kmin_pk: 0.005
  ampnorm_pk: False
  offset_amp_pk: 1.e+4
  kmax_bk: 0.5
  kmin_bk: 0.005
  ampnorm_bk: False
  offset_amp_bk: False
  reduced: False
  logit: False
  standardize: True
  ngals: True

analysis:
  seed: 0
  train_fraction: 0.85
  validation_fraction: 0.06
  fithod: True
  standardize_hod: True
  suffix: "-train94"
  ndiagnostics: 5